apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-blue-green-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Aseenanizar/argorollouttest.git'
    targetRevision: HEAD
    path: 'kubernetes/deployments/blue-green'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
